# Generated by Django 4.0.6 on 2023-03-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='branch',
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('terminal_no', models.PositiveIntegerField()),
                ('port', models.IntegerField(default=9100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('printer', models.CharField(choices=[('KITCHEN', 'KITCHEN'), ('BAR', 'BAR')], max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
            ],
            options={
                'unique_together': {('printer', 'terminal_no')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='terminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.terminal'),
            preserve_default=False,
        ),
    ]
