# Generated by Django 4.0.6 on 2023-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_table_branch_terminal_table_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
