# Generated by Django 4.0.6 on 2023-03-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_terminal_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PrinterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('printer_location', models.CharField(choices=[('KITCHEN', 'KITCHEN'), ('BAR', 'BAR')], max_length=10)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='port',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='url',
        ),
    ]
