# Generated by Django 4.0.6 on 2023-03-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_terminal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printersettings',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='printersettings',
            unique_together={('printer_location', 'terminal')},
        ),
    ]
