# Generated by Django 4.0.6 on 2023-05-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_rename_printersettings_printersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersetting',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
