# Generated by Django 4.0.6 on 2023-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reconcile',
            field=models.BooleanField(default=False),
        ),
    ]
