# Generated by Django 4.0.6 on 2023-05-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_produced',
            field=models.BooleanField(default=True),
        ),
    ]
