# Generated by Django 4.0.6 on 2023-05-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='a', verbose_name='Item Slug'),
            preserve_default=False,
        ),
    ]
