# Generated by Django 4.0.6 on 2023-02-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
