# Generated by Django 4.0.6 on 2023-05-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miti', models.CharField(max_length=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_year', models.CharField(max_length=15, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.assetpurchaseitem')),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalYearSubLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_ledger_name', models.CharField(max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountledger')),
            ],
            options={
                'unique_together': {('sub_ledger_name', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYearLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_name', models.CharField(max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('account_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountchart')),
            ],
            options={
                'unique_together': {('ledger_name', 'fiscal_year')},
            },
        ),
    ]
